### ISSUE TITLE
POSTGRESQL_MAX_CONNECTIONS should not set max_prepared_transactions

### ISSUE THREAD

**Issue by praiskup** [openshift/postgresql#65]
This is wrong design -- each configuration option should have its own
variable.  FWIW, turning prepared transaction _off_ by default is suggested by
PostgreSQL upstream:
http://www.postgresql.org/docs/9.4/static/runtime-config-resource.html

**Comment by mfojtik** [comment]
+1 mind sending PR to fix it?

**Comment by pkajaba** [comment]
Is it this still actual? I can take a look on it

**Comment by mnagy** [comment]
@pkajaba feel free to take a shot at it

**Comment by pkajaba** [comment]
We can close this issue, right?
